
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fanpic
  username: fanpic
  password: fanpic

test:
  <<: *default
  database: fanpic_test
  username: fanpic_test
  password: fanpic_test

production:
  <<: *default
